### ISSUE TITLE
抽卡连接失效后不能再次导入

### ISSUE THREAD

**Issue by Copaan** [monsterxcn/nonebot-plugin-gachalogs#3]
建议增加更新抽卡链接重新导入功能

**Comment by monsterxcn** [comment]
理论上来说应该是可以再次导入的啊。

你的 nonebot 版本是多少？

最近比较忙可能没时间管这个插件。

临时解决办法是重新发送命令的同时附带新的抽卡记录连接，这样应该🆗：

> `抽卡记录 https://www.xxx...`

**Comment by Copaan** [comment]
nonebot2beta2，临时方法可以
