### ISSUE TITLE
插件加载不了

### ISSUE THREAD

**Issue by krasus1995** [monsterxcn/nonebot-plugin-gachalogs#8]
![image](https://user-images.githubusercontent.com/97447697/221755693-da93fade-f94c-44f0-88e2-8e4d2abf4b20.png)

**Comment by monsterxcn** [comment]
https://github.com/monsterxcn/nonebot-plugin-gachalogs/commit/a9d51edc3c45305ad46f5395bc464c4f3a0d1be5 错误地修改了判断顺序，等我有空将其恢复过来。

你暂时可以先手动下载一次 [GachaEvent.json](https://cdn.monsterx.cn/bot/gachalogs/GachaEvent.json) 放到 `data/gachalogs` 文件夹下面。
